In [1]:
!pip install albumentations

In [ ]:
import os
from Part_1.dataset.potholes_dataset import PotholeDataset

if __name__ == "__main__":
    # Adjust path to your actual dataset location

    ROOT = os.path.abspath("potholes")

    if os.path.exists(ROOT):
        train_loader, _, _ = PotholeDataset.create_dataloaders(ROOT)
        img, target = next(iter(train_loader))
        print(f"Loaded batch of {len(img)} images")
        print(f"Image dimensions: {img[0].shape}")
    else:
        print(f"Dataset not found at {ROOT}. Please check path.")

for t in target:
    print(t['boxes'])


Dataset Split: 465 train, 99 val, 101 test
Loaded batch of 4 images
Image dimensions: torch.Size([3, 500, 500])
tensor([[116.6667, 375.0000, 222.2222, 433.3333],
        [180.0000, 311.6667, 240.0000, 331.6667]])
tensor([[141.2500, 248.7500, 200.0000, 280.0000],
        [190.0000, 222.5000, 282.5000, 272.5000],
        [277.5000, 203.7500, 348.7500, 250.0000],
        [462.5000, 115.0000, 500.0000, 160.0000]])
tensor([[  0.9363, 311.6667, 176.0300, 460.0000],
        [ 95.5056, 140.0000, 264.9813, 251.6667],
        [  0.9363,  91.6667, 134.8315, 221.6667],
        [156.3671,  73.3333, 230.3371, 113.3333],
        [295.8801,  45.0000, 500.0000, 150.0000],
        [277.1536, 145.0000, 433.5206, 231.6667],
        [342.6966, 283.3333, 500.0000, 458.3333],
        [  0.9363,  41.6667, 110.4869,  88.3333]])
tensor([[170.0000, 137.5000, 337.5000, 325.0000],
        [287.5000, 147.5000, 350.0000, 212.5000],
        [260.0000,  20.0000, 302.5000,  46.2500],
        [ 41.2500,  21.2500,  85.00